const CODE_OK = 0;
const CODE_INVALID_ADDRESS = 1;
const CODE_INVALID_DATE = 2;
const CODE_INVALID_BLOCK = 3;
const CODE_INVALID_AUTHORIZATION = 4;
const CODE_INTERNAL = 100;

export {
  CODE_OK,
  CODE_INVALID_ADDRESS,
  CODE_INVALID_DATE,
  CODE_INVALID_BLOCK,
  CODE_INVALID_AUTHORIZATION,
  CODE_INTERNAL,
};