CREATE TABLE IF NOT EXISTS user_nft_shield (
    uid INTEGER PRIMARY KEY REFERENCES "user"(id_user) ON DELETE CASCADE,
    pin_hash VARCHAR(255) NOT NULL,
    failed_attempts INTEGER DEFAULT 0,
    lock_until TIMESTAMP DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
