package com.senspark.game.declare

object SFSField {
    const val ErrorString: String = "es" // (string)
    const val ErrorCode: String = "ec" // (int)
    const val LocParam: String = "lp"
    const val Tag: String = "tag"

    const val SfsId: String = "sfs_id"
    const val User_Id: String = "user_id"
    const val User_Name: String = "pln"
    const val TelegramData: String = "telegram_data"
    const val SecondUsername: String = "second_username"
    const val BomberName: String = "name"
    const val Password: String = "password"
    const val LoginType: String = "lt"
    const val DeviceType: String = "device_type"
    const val DataType: String = "data_type"
    const val Landing: String = "landing" // client field: mode chơi của phiên (treasure|adventure)
    const val LandingSession: String = "landing_session" // session property bắc cầu landing từ login sang join zone
    const val ForceLogin: String = "force_login" // client field: yêu cầu kick phiên cũ để chiếm chỗ
    const val ForceLoginSession: String = "force_login_session" // session property bắc cầu force_login từ login sang admission
    const val Platform: String = "platform"
    const val Token: String = "token"
    const val Slogan: String = "slogan"
    const val UserInfo: String = "userInfo"
    const val signature: String = "signature"
    const val Login_Code: String = "lc"
    const val TelegramUserData: String = "telegram_user_data"
    const val REFERRAL_CODE: String = "referral_code"

    const val Version_Code: String = "version_code"
    const val Guest_UId: String = "key_guest_uid"

    //
    const val Gold: String = "gold"
    const val Rank: String = "rank"
    const val Leaderboard: String = "leaderboard"
    const val My_Rank: String = "my_rank"
    const val UserOnlineInLobby: String = "UserOnlineInLobby"
    const val Pvp_Invite_Answer: String = "answer"

    const val Name: String = "name"
    const val ID: String = "id"
    const val SERVER_PLAYING: String = "SERVER_PLAYING"
    const val NewUser: String = "new_user"
    const val Clan_Data: String = "clan_data"
    const val Leader_Name: String = "leader_name"
    const val Level: String = "level"
    const val Join_Freely: String = "join_freely"
    const val Members: String = "members"
    const val Limit_Members: String = "limit_members"
    const val Role: String = "role"
    const val Clan_Info: String = "clan_info"
    const val IsOnline: String = "is_online"
    const val Datas: String = "datas"
    const val IsApprove: String = "is_approve"
    const val ClanPoint: String = "clan_point"
    const val Reply: String = "reply"
    const val Exp: String = "exp"
    const val LimitExp: String = "limit_exp"
    const val GoldUpgrade: String = "gold_upgrade"
    const val GoldDonate: String = "gold_donate"
    const val STAGE: String = "stage"
    const val ADDRESS: String = "address"
    const val SEND_LOG: String = "send_log"

    const val PosX: String = "posx"
    const val PosY: String = "posy"
    const val TotalGold: String = "total_gold"

    const val USER_ID: String = "user_id"
    const val USER_NAME: String = "pln"
    const val SECOND_USER_NAME: String = "username"
    const val PASSWORD: String = "password"
    const val INVESTED: String = "invested"
    const val MINED: String = "mined"
    const val ROI: String = "roi"
    const val POSITION: String = "position"
    const val PLAYER_CONTROLLER: String = "players"
    const val MATCH_INFO: String = "match_info"
    const val LIFE: String = "life"
    const val IS_WIN: String = "is_win"
    const val Station: String = "station"
    const val UsersInDesk: String = "users_in_desk"
    const val MyDatas: String = "my_data"

    const val Bombers: String = "bombers"
    const val Bomber: String = "bomber"
    const val NewBombers: String = "new_bombers"
    const val DeletedBombers: String = "deleted_bombers"
    const val ForceFresh: String = "forceFresh"
    const val GenID: String = "gen_id"
    const val TxHash: String = "tx_hash"

    //	public static final String BomberID = "bomber_id";
    const val Power: String = "power"
    const val BombRange: String = "bomb_range"
    const val Stamina: String = "stamina"
    const val Speed: String = "speed"
    const val Bomb: String = "bomb"
    const val Ability: String = "ability"
    const val Charactor: String = "charactor"
    const val Color: String = "color"
    const val Rare: String = "rare"
    const val BombSkin: String = "bomb_skin"
    const val Energy: String = "energy"
    const val Blocks: String = "blocks"
    const val Tileset: String = "tileset"
    const val HP: String = "hp"
    const val Type: String = "type"
    const val Value: String = "value"
    const val HERO_QUANTITY: String = "hero_quantity"
    const val Rewards: String = "rewards"
    const val AMOUNT: String = "amount"
    const val CHAIN: String = "chain"
    const val AmountOfBcoin: String = "amount_of_bcoin"
    const val AmountOfBcoinClaimed: String = "amount_of_bcoin_claimed"
    const val Stage: String = "stage"
    const val ALL_IN: String = "all_in"
    // SYNC_DEPOSITED_V4 routing: "OLD" | "BRIDGE" | "BOTH". Absent → BOTH.
    const val DEPOSIT_SYNC_TARGET: String = "deposit_sync_target"
    // Cross-chain bridge withdraw-sign response (Phase 9): the user relays withdraw(...) themselves.
    const val OTHER_DEPOSITED: String = "other_deposited"
    const val DEADLINE: String = "deadline"
    const val BRIDGE_ADDRESS: String = "bridge_address"
    const val TOKEN_ADDRESS: String = "token_address"

    // Native withdraw-sign response: the user relays withdraw(allowed_cumulative, deadline, signature).
    const val ALLOWED_CUMULATIVE: String = "allowed_cumulative"
    const val CONTRACT_ADDRESS: String = "contract_address"
    const val CHAIN_ID: String = "chain_id"
    // Cross-chain bridge activity notify (Phase 9 smart-sweep): which activity + the on-chain tx hash.
    const val KIND: String = "kind"
    const val TX_HASH: String = "tx_hash"

    // linhpd sửa từ House_Gen_Id => House_Id
    const val House_Gen_Id: String = "house_gen_id"
    const val House_Id: String = "house_id"
    const val Active: String = "active"
    const val Charge: String = "charge"
    const val Max_Slot: String = "max_slot"
    const val Restore_HP: String = "restore_hp"
    const val Houses: String = "houses"
    const val NewHouses: String = "new_houses"
    const val Received: String = "received"
    const val Remaining: String = "remaining"
    const val RemainTime: String = "remain_time"
    const val Cost: String = "cost"
    const val BLOCK_REWARD_TYPE: String = "block_reward_type"
    const val IS_WITHDRAW: String = "is_withdraw"
    const val HERO_IDS: String = "hero_ids"
    const val TOKEN_TYPE: String = "token_type"
    const val COIN_DETAIL: String = "coin_details"
    const val BCOIN_IN_WALLET: String = "bcoin_in_wallet"
    const val TOTAL_STAKED: String = "total_staked"
    const val PRINCIPAL: String = "principal"
    const val PROFIT: String = "profit"
    const val STAKE_DATE: String = "stake_date"
    const val WITHDRAW_FEE: String = "withdraw_fee"
    const val TOTAL_STAKE: String = "total_stake"
    const val APD: String = "apd"
    const val RECEIVE_AMOUNT: String = "receive_amount"
    const val IsDangerous: String = "is_dangerous"
    const val HeroType: String = "hero_type"
    const val Shields: String = "shields"
    const val ActivationCode: String = "activation_code"
    const val RequestId: String = "requestId"
    const val StakeBcoin: String = "stake_bcoin"
    const val StakeSen: String = "stake_sen"

    const val BanExpireAt: String = "ban_expire_at"
    const val LoginTokenData: String = "lk"
    const val Data: String = "data"
    const val NewRequestId: String = "rid"
}