const CODE_OK = 0;
const CODE_BAD_REQUEST = 1;
const CODE_INVALID_ADDRESS = 2;
const CODE_INVALID_AUTHORIZATION = 4;
const CODE_INTERNAL = 100;

export {
  CODE_OK,
  CODE_BAD_REQUEST,
  CODE_INVALID_ADDRESS,
  CODE_INVALID_AUTHORIZATION,
  CODE_INTERNAL,
};
