networks:
  base_default:
    external: true

name: bombcrypto
services:

  ap-native-rate-keeper:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_VERSION: ${APP_VERSION:-dev}
    container_name: ap-native-rate-keeper
    ports:
      - "8111:80"
    networks:
      - base_default
    env_file:
      - .env
    environment:
      TZ: 'Asia/Bangkok'
      PORT: '80'
      IS_PROD: false
      REDIS_CONNECTION_STRING: 'redis://@redis:6379/0'
    restart: unless-stopped
